### ISSUE TITLE
Update Suunto "RACE acidotic & Win" Tile Photo

### ISSUE THREAD

**Issue by ChrisJDunn** [theWickedWebDev/acidotic-racing#5]
Please update the tile photo.

**Comment by theWickedWebDev** [comment]
do you mean the same photo that is on the current site?

**Comment by ChrisJDunn** [comment]
Yes.

**Comment by theWickedWebDev** [comment]
![suunto_img](https://cloud.githubusercontent.com/assets/7525324/6140445/d191a0cc-b165-11e4-8e29-1b00cd02052c.jpg)

**Comment by theWickedWebDev** [comment]
thanks!
